Add iam auth support
viktor-zinchenko/php-graphql-client pull request #1
Opened 2021-07-09 18:38 UTC by viktor-zinchenko

2021-07-15 14:20 UTC, dmitrykiselev27 reviewed
Looks good to me

2021-07-15 14:20 UTC, dmitrykiselev27 commented on src/Client.php
> +        string $authType,
If that was the PR to upstream I would say to move this argument to the bottom and add the default value to keep the backward compatibility. But since it's our private fork, maybe, the current implementation is fine.

2021-07-15 14:21 UTC, dmitrykiselev27 approved these changes

2021-07-16 13:02 UTC, manuel-work requested changes
There are a LOT of unrelated / cosmetic changes on this PR, which makes the PR harder to review, as well as makes tracking upstream harder. Can clean this up so that we only introduce the necessary changes ?

2021-07-16 13:09 UTC, manuel-work commented on src/Client.php
> +        string $authType,
I agree, and even though this is a private fork, it takes little effort to do this. We'd maintain backwards compatibility, which at least will not negatively affect the chances of getting this committed upstream.

2021-07-16 13:29 UTC, viktor-zinchenko commented on src/Client.php
> +        string $authType,
I agree, will have a look

2021-07-19 20:26 UTC, viktor-zinchenko commented on src/Client.php
> +        string $authType,
Made changes to keep backwards compatibility

2021-07-19 20:27 UTC, viktor-zinchenko commented
> There are a LOT of unrelated / cosmetic changes on this PR, which makes the PR harder to review, as well as makes tracking upstream harder. Can we clean this up so that we only introduce the necessary changes ?

Removed unrelated changes

2021-07-20 09:14 UTC, merged

2021-07-20 10:16 UTC, manuel-work reviewed
Looks good to me, found only a couple of (minor) things.

2021-07-20 10:16 UTC, manuel-work commented on src/Auth/AwsIamAuth.php
> +     */
Minor: This is documented in the interface, no need to duplicate the docblock in my opinion.

2021-07-20 10:16 UTC, manuel-work commented on src/Auth/HeaderAuth.php
> +     */
Same, no need for the duplicated docblock